// Default student names — edit this file and redeploy to change the permanent list.
// Or use the Settings page to override via Vercel KV (no redeploy needed).
export const DEFAULT_NAMES = [
  { nama: 'ADIVA KAYRA RIYADI', gender: 'P' },
  { nama: 'ALANDRA SHAZIA MAULASATHI', gender: 'P' },
  { nama: 'ALMIRA DEWI PRATISTA SULANJANI', gender: 'P' },
  { nama: 'ATTALA ANDAFINO', gender: 'L' },
  { nama: 'AURELLIA TALITA SAKHI', gender: 'P' },
  { nama: 'BRAYAN SINGAJIWA', gender: 'L' },
  { nama: 'CETTA KHANZA RAFANY', gender: 'P' },
  { nama: 'DAFFA MUTAHA', gender: 'L' },
  { nama: 'FAIZA LUBNA MAZAYA', gender: 'P' },
  { nama: 'FATIHUL ULUM', gender: 'L' },
  { nama: 'FITRIANI FATIMATHUL ZAHRO IRAWAN', gender: 'P' },
  { nama: 'GEYSA KARENDIA MADE', gender: 'P' },
  { nama: 'HAFIZHAH YASMIN SIREGAR', gender: 'P' },
  { nama: 'JASMINE AIMAN FIRZANI', gender: 'P' },
  { nama: 'KAILA DAVINA MARUF', gender: 'P' },
  { nama: 'KIRANADEWI NASUTION', gender: 'P' },
  { nama: 'MALVA KHALIFATI BANAFSAJ', gender: 'P' },
  { nama: 'MUHAMMAD FACHDI HAMZI', gender: 'L' },
  { nama: 'MUHAMMAD FAHRIE AL GHOZALI', gender: 'L' },
  { nama: 'MUHAMMAD FIRZA AL-HAFIDZ', gender: 'L' },
  { nama: 'MUHAMMAD MUDZAKIR', gender: 'L' },
  { nama: 'NADA KHOLISAH', gender: 'P' },
  { nama: 'NADIRA HIKMATUL ULYA', gender: 'P' },
  { nama: 'NAZIERA MUSTAQIMAH', gender: 'P' },
  { nama: 'NOVAL TANJUNG', gender: 'L' },
  { nama: 'PANDU PUTRA PUJANGGA', gender: 'L' },
  { nama: 'NUZULLA WADHA MARITZA', gender: 'P' },
  { nama: 'OLANNA KAMILA HADI', gender: 'P' },
  { nama: 'RATU NURUL KHOFIPAH', gender: 'P' },
  { nama: 'REINA ALMIRA FIRNAS', gender: 'P' },
  { nama: 'RIMA CAHYANI', gender: 'P' },
  { nama: 'SALSABILA ANANDA SUHARTA', gender: 'P' },
  { nama: 'SHAFFIRA PUTRI VALENTINE', gender: 'P' },
  { nama: 'SHAFIYYAH GHAISANI HARJANTO', gender: 'P' },
  { nama: 'WARDATUL JAMILAH AL-AHMARI', gender: 'P' },
  { nama: 'ZAHIRAH DEGES RAELI SIREGAR', gender: 'P' },
];
